### ISSUE TITLE
Loading fails - v3.1.1 (HA2023.2.0)

### ISSUE THREAD

**Issue by buhito81** [amosyuen/ha-tplink-deco#150]
### Problem

Loading fails:

```
Unexpected error fetching tplink_deco-decos data: async_call_with_retry() missing 1 required positional argument: 'args'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 171, in _async_update_data
    new_decos = await async_call_with_retry(self.api, self.api.async_list_devices)
TypeError: async_call_with_retry() missing 1 required positional argument: 'args'
```

### TP-Link Deco Version

M5, Hardware 3

### Router Model

Firmware: 1.6.1 Build 20220818 Rel. 36456

### Debugging Information

```
Unexpected error fetching tplink_deco-decos data: async_call_with_retry() missing 1 required positional argument: 'args'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 171, in _async_update_data
    new_decos = await async_call_with_retry(self.api, self.api.async_list_devices)
TypeError: async_call_with_retry() missing 1 required positional argument: 'args'
```

**Comment by amosyuen** [comment]
Thanks for catching this, fix in v3.1.2
