### ISSUE TITLE
KeyError: 'client_prefix'

### ISSUE THREAD

**Issue by tjorim** [amosyuen/ha-tplink-deco#191]
Using version 3.4.0 the client prefix is not optional:
```
Logger: homeassistant.components.device_tracker
Source: custom_components/tplink_deco/device_tracker.py:70
Integration: Device Tracker (documentation, issues)
First occurred: 11:50:07 (1 occurrences)
Last logged: 11:50:07

Error while setting up tplink_deco platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tplink_deco/device_tracker.py", line 70, in async_setup_entry
    client_prefix = entry.data[CONF_CLIENT_PREFIX]
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'client_prefix'
```

**Comment by Gferretta** [comment]
Hi
Idem with postfix :(
Any solution?   
HA 2023.7.1


`Logger: homeassistant.components.device_tracker
Source: custom_components/tplink_deco/device_tracker.py:71
Integration: Rastreador de dispositivos (documentation, issues)
First occurred: 00:41:47 (1 occurrences)
Last logged: 00:41:47

Error while setting up tplink_deco platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tplink_deco/device_tracker.py", line 71, in async_setup_entry
    client_postfix = entry.data[CONF_CLIENT_POSTFIX]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'client_postfix'
`

**Comment by amosyuen** [comment]
Should be fixed in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.4.1
