### ISSUE TITLE
Error setting up

### ISSUE THREAD

**Issue by gielk** [amosyuen/ha-tplink-deco#234]
### Problem

I am having a problem installing the TP-Link. I have tried rebooting the routers and increasing the timeout and retry settings, but I still can't get it to install.

```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 09:25:01 (1 occurrences)
Last logged: 09:25:01

Error setting up entry 192.168.178.1 for tplink_deco
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 161, in async_setup_entry
    data = await async_create_config_data(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 144, in async_create_config_data
    return await async_create_and_refresh_coordinators(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 98, in async_create_and_refresh_coordinators
    await clients_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 246, in _async_update_data
    deco_client_responses = await asyncio.gather(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 47, in async_call_and_propagate_config_error
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 221, in async_list_clients
    return await self._async_call_with_retry(self._async_list_clients, deco_mac)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 544, in _async_call_with_retry
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 228, in _async_list_clients
    response_json = await self._async_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 409, in _async_post
    response = await self._session.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: aiohttp connection lost

```

### TP-Link Deco Version

3.6.10 iOS app

### Router Model

Deco M4R

### Debugging Information

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 09:25:01 (1 occurrences)
Last logged: 09:25:01

Error setting up entry 192.168.178.1 for tplink_deco
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 161, in async_setup_entry
    data = await async_create_config_data(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 144, in async_create_config_data
    return await async_create_and_refresh_coordinators(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 98, in async_create_and_refresh_coordinators
    await clients_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 246, in _async_update_data
    deco_client_responses = await asyncio.gather(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 47, in async_call_and_propagate_config_error
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 221, in async_list_clients
    return await self._async_call_with_retry(self._async_list_clients, deco_mac)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 544, in _async_call_with_retry
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 228, in _async_list_clients
    response_json = await self._async_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 409, in _async_post
    response = await self._session.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: aiohttp connection lost

**Comment by amosyuen** [comment]
Include debugging logs from https://github.com/amosyuen/ha-tplink-deco/blob/main/DEBUGGING.md

**Comment by amosyuen** [comment]
Closing since no debugging logs
