### ISSUE TITLE
TP-Link Deco Not reporting to HA that a device is on the network

### ISSUE THREAD

**Issue by mikefrantz** [amosyuen/ha-tplink-deco#276]
### Problem

Not reporting to HA that a device is on the network. It is always not_home on my devices. I do know that TP-Link did an update on there app.

### TP-Link Deco Version

3.6.0

### Router Model

Deco X55

### Debugging Information

not_home
icon: mdi:lan-disconnect
friendly_name: iPhone Mike
source_type: router
ip: 192.168.68.106
mac: 8E-18-51-37-67-12
connection_type: band2_4
device_type: client
interface: main
down_kilobytes_per_s: 0
up_kilobytes_per_s: 0
deco_device: Entryway
deco_mac: 9C-53-22-CC-34-48

**Comment by EboBH83** [comment]
I have the same issue, but clearly it's a deco issue and this integration can't fix it. The NMAP and Ping integrations are more reliable anyway in sensing Home/Away, but this one is still indispensable for sensing much more data.
I contacted TP-Link, and they sent an update file they said would fix the issue.

**Comment by mikefrantz** [comment]
Did TP Link send you the fie to fix the issue and if they did, did it work? If it worked can you advise me on exactly what file to ask for and who you contacted please? Thanks for all your help. Have a great New Year.

**Comment by EboBH83** [comment]
I didn't install it, and opted to wait for an update that'd fix it automatically. That was a false hope, as the device received two or three updates that didn't fix nothing.  I would send you the update file they sent me, but you most probably have a different device. Contact them via: https://community.tp-link.com/

**Comment by mikefrantz** [comment]
I received a TP link update today for Home Assistant and it did not fix it. Thanks for all your help. I appreciate it.

**Comment by EboBH83** [comment]
> I received a TP link update today for Home Assistant and it did not fix it. Thanks for all your help. I appreciate it.

So I shouldn't bother installing it either. Thanks for saving me that time.

**Comment by mikefrantz** [comment]
![Uploading IMG_1863.jpeg…]() here is what it looks like after the update installed. I have to re load the tp-link integration about every 3 minutes to keep any kind of location services. Thanks

**Comment by EboBH83** [comment]
My issue is different. My Deco devices report the info it had when it first started and does change that, no even with a reload. Even the Deco app reports the same info. The only way to get around that is a restart of the Deco network.

**Comment by mikefrantz** [comment]
That is good to know. Mine just goes unavailable continually and will never change states after that. I have to reload integration continually with an automation. Then if that doesn’t work, then I have to restart home assistance. Then if that doesn’t work, then I have to reboot the TP-Link unit itself.

**Comment by EboBH83** [comment]
tried this?
![Untitled](https://github.com/user-attachments/assets/72af600e-8ae0-447d-9326-1e41751fb7c2)

**Comment by mikefrantz** [comment]
Here is the latest error logs. Hope you can shed some light on this.

This error originated from a custom integration.

Logger: custom_components.tplink_deco.coordinator
Source: helpers/update_coordinator.py:379
integration: TP-Link Deco (documentation, issues)
First occurred: 7:08:08 AM (284 occurrences)
Last logged: 3:57:13 PM

Unexpected error fetching tplink_deco-decos data
Unexpected error fetching tplink_deco-clients data
Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 409, in _async_post
    response = await self._session.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 730, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 671, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 408, in _async_post
    async with async_timeout.timeout(self._timeout_seconds):
               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 167, in _async_update_data
    new_decos = await async_call_and_propagate_config_error(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.async_list_devices
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/tplink_deco/coordinator.py", line 48, in async_call_and_propagate_config_error
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 166, in async_list_devices
    return await self._async_call_with_retry(self._async_list_devices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 557, in _async_call_with_retry
    raise err
  File "/config/custom_components/tplink_deco/api.py", line 544, in _async_call_with_retry
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 173, in _async_list_devices
    response_json = await self._async_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/config/custom_components/tplink_deco/api.py", line 445, in _async_post
    raise TimeoutException from err
custom_components.tplink_deco.exceptions.TimeoutException: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.

**Comment by cihancemaloglu** [comment]
I'm experiencing the same issue as @mikefrantz. I think the issue is related with integration.

<img width="728" height="788" alt="Image" src="https://github.com/user-attachments/assets/6b53a097-907c-45a0-b514-7ebd96869e14" />

Also tried what @EboBH83 suggested.

<img width="745" height="589" alt="Image" src="https://github.com/user-attachments/assets/326c6b5c-8b36-4f6c-b63f-924f0540a87c" />
