### ISSUE TITLE
Unexpected error fetching tplink_deco-clients data

### ISSUE THREAD

**Issue by jonahgcarpenter** [amosyuen/ha-tplink-deco#294]
### Problem

the integration fails to start and the log shows the error described 

### TP-Link Deco Version

3.6.2

### Router Model

Deco X55

### Debugging Information

This error originated from a custom integration.

Logger: custom_components.tplink_deco.coordinator
Source: helpers/update_coordinator.py:315
integration: TP-Link Deco (documentation, issues)
First occurred: 7:54:53 PM (82 occurrences)
Last logged: 11:06:55 PM

Unexpected error fetching tplink_deco-clients data
Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 409, in _async_post
    response = await self._session.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 408, in _async_post
    async with async_timeout.timeout(self._timeout_seconds):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 246, in _async_update_data
    deco_client_responses = await asyncio.gather(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/coordinator.py", line 47, in async_call_and_propagate_config_error
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 221, in async_list_clients
    return await self._async_call_with_retry(self._async_list_clients, deco_mac)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 557, in _async_call_with_retry
    raise err
  File "/config/custom_components/tplink_deco/api.py", line 544, in _async_call_with_retry
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 228, in _async_list_clients
    response_json = await self._async_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/api.py", line 445, in _async_post
    raise TimeoutException from err
custom_components.tplink_deco.exceptions.TimeoutException: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.

**Comment by RoiS8** [comment]
Have you tired changing the [timeout seconds](https://github.com/amosyuen/ha-tplink-deco?tab=readme-ov-file#timeout-seconds) or the [timeout error retry count](https://github.com/amosyuen/ha-tplink-deco#timeout-error-retry-count) in the integration config?
