### ISSUE TITLE
Unable to reach host 502 error

### ISSUE THREAD

**Issue by DiGiSoUL84** [amosyuen/ha-tplink-deco#296]
### Problem

For the last couple of days, the integration has failed to initialize. Every attempt errors out and I keep getting the following error:  Error connection to host: 502, message='Bad Gateway', url=URL('http://192.168.24.1/cgi-bin/luci/;stok=c916c8f7fc0a29776a9cf660488e48f3/admin/client?form=client_list')

### TP-Link Deco Version

v3.6.2

### Router Model

Deco W6000, Deco MR4

### Debugging Information

2024-05-31 07:25:11.653 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:25:11.653 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (1 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:25:11.656 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:25:11.657 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (1 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:25:11.658 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:25:11.658 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (1 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:25:35.985 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('tplink_deco', '3c4c31b3d9df8ee0110262bb7da62ae8'): 16573.495437594}
2024-05-31 07:25:42.655 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:25:42.655 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (2 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:25:42.658 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:25:42.658 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (2 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:25:42.659 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:25:42.660 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (2 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:13.657 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:26:13.657 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (3 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:13.659 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:26:13.659 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (3 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:13.661 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:26:13.661 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (3 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:36.034 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('tplink_deco', '3c4c31b3d9df8ee0110262bb7da62ae8'): 16573.495437594}
2024-05-31 07:26:44.659 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:26:44.659 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (4 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:44.661 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:26:44.662 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (4 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:26:44.663 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:26:44.663 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (4 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:15.662 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:27:15.662 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (5 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:15.665 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:27:15.665 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (5 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:15.666 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:27:15.666 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (5 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:36.091 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('tplink_deco', '3c4c31b3d9df8ee0110262bb7da62ae8'): 16573.495437594}
2024-05-31 07:27:46.665 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:27:46.665 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (6 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:46.667 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:27:46.667 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (6 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:27:46.669 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:27:46.669 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (6 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:17.667 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:28:17.667 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (7 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:17.669 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:28:17.669 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (7 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:17.671 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:28:17.671 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (7 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:36.145 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('tplink_deco', '3c4c31b3d9df8ee0110262bb7da62ae8'): 16573.495437594}
2024-05-31 07:28:48.670 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:28:48.670 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (8 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:48.672 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:28:48.672 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (8 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:28:48.674 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:28:48.674 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (8 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:29:19.672 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 5C-E9-31-4C-95-DC timed out
2024-05-31 07:29:19.673 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (9 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:29:19.675 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D8 timed out
2024-05-31 07:29:19.675 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (9 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:29:19.677 DEBUG (MainThread) [custom_components.tplink_deco.api] List Clients 10-27-F5-E7-96-D4 timed out
2024-05-31 07:29:19.677 DEBUG (MainThread) [custom_components.tplink_deco.api] Retry (9 of 10) timeout error: Timeout exception. If you get a lot of these see https://github.com/amosyuen/ha-tplink-deco#timeout-error.
2024-05-31 07:29:36.201 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('tplink_deco', '3c4c31b3d9df8ee0110262bb7da62ae8'): 16573.495437594}
2024-05-31 07:29:36.733 DEBUG (MainThread) [custom_components.tplink_deco.coordinator] Finished fetching tplink_deco-clients data in 296.084 seconds (success: True)
2024-05-31 07:29:36.733 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.24.1 for tplink_deco
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/__init__.py", line 161, in async_setup_entry
data = await async_create_config_data(hass, config_entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/__init__.py", line 144, in async_create_config_data
return await async_create_and_refresh_coordinators(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/__init__.py", line 98, in async_create_and_refresh_coordinators
await clients_coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in async_config_entry_first_refresh
await self._async_refresh(
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/coordinator.py", line 246, in _async_update_data
deco_client_responses = await asyncio.gather(
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/coordinator.py", line 47, in async_call_and_propagate_config_error
return await func(*args)
^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/api.py", line 221, in async_list_clients
return await self._async_call_with_retry(self._async_list_clients, deco_mac)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/api.py", line 544, in _async_call_with_retry
return await func(*args)
^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/api.py", line 228, in _async_list_clients
response_json = await self._async_post(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tplink_deco/api.py", line 409, in _async_post
response = await self._session.post(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
await resp.start(conn)
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
message, payload = await protocol.read() # type: ignore[union-attr]
^^^^^^^^^^^^^^^^^^^^^

**Comment by DiGiSoUL84** [comment]
@Phil-oss-bot  I was unable to find a resolution. I was gifted an ASUS router and a couple ASUS Access Points by my father-in-law so I redid my entire network.
