### ISSUE TITLE
Error in HA setup

### ISSUE THREAD

**Issue by AndersHub** [amosyuen/ha-tplink-deco#30]
I get this error when I start up HA.

Logger: homeassistant.setup
Source: components/device_tracker/legacy.py:302
First occurred: 20:02:41 (1 occurrences)
Last logged: 20:02:41

Error during setup of component device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/__init__.py", line 48, in async_setup
    await async_setup_legacy_integration(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 158, in async_setup_integration
    legacy_platforms = await async_extract_config(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 302, in async_extract_config
    raise ValueError(
ValueError: Unable to determine type for tplink_deco: None

Any idea what goes wrong or what I do wrong?

My configuration.yaml is simple as follows:
device_tracker:
  - platform: tplink_deco
    host: 192.168.xx.1
    username: at@xxx
    password: xxxxx
    interval_seconds: 5
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

**Comment by amosyuen** [comment]
Integration only supports UI config flow

**Comment by AndersHub** [comment]
Yes I understand that. The only thing I have done is to put the code in configuration.yaml as you see in the template. I am a beginner so I will appreciate if you can give me some help.

**Comment by amosyuen** [comment]
I'm saying that you can NOT use configuration.yaml, you must use the UI flow, did you follow the last step in the instructions in README https://github.com/amosyuen/ha-tplink-deco#hacs?
