### ISSUE TITLE
'utf-8' codec can't decode byte 0xb8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by amosyuen** [amosyuen/ha-tplink-deco#64]
## Describe the bug

Error setting up config from @[Scoopien](https://github.com/Scoopien)

## Debug log

```text
ste erro teve origem numa integração personalizada.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:198
Integration: TP-Link Deco (documentation, issues)
First occurred: 23:56:36 (3 occurrences)
Last logged: 23:57:44

Unexpected error fetching tplink_deco-clients data: 'utf-8' codec can't decode byte 0xb8 in position 0: invalid start byte
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/tplink_deco/coordinator.py", line 236, in _async_update_data
deco_client_responses = await asyncio.gather(
File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
return await func(*args)
File "/config/custom_components/tplink_deco/api.py", line 198, in async_list_clients
client["name"] = base64.b64decode(client["name"]).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 0: invalid start byte

Este erro teve origem numa integração personalizada.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:57
Integration: TP-Link Deco (documentation, issues)
First occurred: 23:57:44 (1 occurrences)
Last logged: 23:57:44

Error testing credentials: 'utf-8' codec can't decode byte 0xb8 in position 0: invalid start byte
```

**Comment by amosyuen** [comment]
@scoopien Looks like your router is returning some unexpected name value. Please follow advanced debugging steps at https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md to verify what your list client response from Admin UI look like.
