### ISSUE TITLE
Device without IP, but friendly_name as IP

### ISSUE THREAD

**Issue by gmaslowski** [amosyuen/ha-tplink-deco#98]
## Version of the custom_component
2.2.0

## Deco Model
P9

## Describe the bug

I have 2xP9 setup. Both working as APs and meshing each other.

One of the devices on the connected devices list has **friendly_name** as the **ip**. 

![image](https://user-images.githubusercontent.com/1597459/187038842-152af3a5-3deb-4eac-8e1f-62981ee25175.png)

I know it seems that Deco is doing something weird. But I'm not sure how to proceed with that problem. Any help?

## Debug log

That causes the integration to fail with:

```
2022-08-27 16:10:04.445 ERROR (MainThread) [homeassistant.helpers.event] Error while processing event <Event state_changed[L]: entity_id=device_tracker.4069446681, old_state=None, new_state=<state device_tracker.4069446681=home; source_type=router, ip=4069446681, mac=34-EA-E7-E5-17-40, connection_type=band2_4, interface=main, down_kilobytes_per_s=0.0, up_kilobytes_per_s=0.0, deco_device=Living Room 1, deco_mac=B0-95-75-F3-D8-FE, device_class=client, icon=mdi:lan-connect, friendly_name=4069446681 @ 2022-08-27T18:10:04.440862+02:00>> for domain device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 419, in _async_dispatch_domain_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 546, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 311, in _async_process_device_event
    self._async_process_device_state(event.data["new_state"])
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 331, in _async_process_device_state
    self.async_process_client(ip_address, hostname, _format_mac(mac_address))
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 155, in async_process_client
    made_ip_address = make_ip_address(ip_address)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: '4069446681' does not appear to be an IPv4 or IPv6 address

```

**Comment by amosyuen** [comment]
Should be fixed in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.2.1.
